## Import csv Data Set

In [1]:
import pandas as pd
df = pd.read_csv('emp.csv')
df

,Employee_ID,Name,Department,Age,Gender,Experience_Years,Work_Mode,Projects_Completed,Avg_Daily_Hours,Performance_Score,Sick_Days,Training_Hours,Job_Satisfaction
0,E001,Amit,IT,29.0,Male,5.0,Remote,12.0,8.5,88.0,3.0,20.0,4.0
1,E002,Sara,HR,34.0,Female,8.0,Office,9.0,7.5,82.0,5.0,15.0,3.0
2,E003,Rahul,Finance,31.0,Male,6.0,Hybrid,11.0,8.0,85.0,2.0,18.0,4.0
3,E004,Priya,IT,27.0,Female,3.0,Remote,8.0,7.8,80.0,1.0,12.0,3.0
4,E005,John,Marketing,36.0,Male,10.0,Office,15.0,9.0,92.0,4.0,22.0,5.0
5,E006,Anita,HR,28.0,Female,4.0,Hybrid,7.0,7.2,75.0,6.0,10.0,2.0
6,E007,Arjun,IT,30.0,Male,6.0,Remote,13.0,8.6,89.0,2.0,20.0,4.0
7,E008,Meera,Finance,33.0,Female,7.0,Office,10.0,8.1,84.0,3.0,17.0,4.0
8,E009,Kiran,Marketing,29.0,Male,5.0,Hybrid,9.0,7.6,78.0,4.0,14.0,3.0
9,E010,David,IT,35.0,Male,9.0,Office,14.0,8.8,91.0,2.0,21.0,5.0
10,E011,Linda,HR,NaN,Female,6.0,Remote,8.0,7.4,76.0,5.0,13.0,3.0
11,E012,Ravi,Finance,32.0,Male,NaN,Hybrid,11.0,8.2,86.0,3.0,18.0,4.0
12,E013,Nina,Marketing,26.0,Female,3.0,Office,7.0,7.1,NaN,4.0,12.0,3.0
13,E014,Sunil,IT,31.0,Male,7.0,Remote,12.0,8.3,87.0,NaN,19.0,4.0
14,E015,Asha,HR,29.0,Female,5.0,Hybrid,9.0,7.7,80.0,3.0,NaN,3.0
15,E016,Karthik,Finance,34.0,Male,8.0,Office,10.0,NaN,83.0,2.0,17.0,4.0
16,E017,Divya,Marketing,27.0,Female,4.0,Remote,8.0,7.3,77.0,5.0,11.0,NaN
17,E018,Joseph,IT,36.0,Male,11.0,Office,16.0,9.1,93.0,2.0,24.0,5.0
18,E019,Anu,HR,30.0,Female,6.0,Hybrid,9.0,7.6,81.0,4.0,14.0,3.0
19,E020,Varun,Finance,28.0,Male,4.0,Remote,NaN,7.5,79.0,3.0,13.0,3.0
20,E021,Riya,Marketing,31.0,Female,6.0,Office,11.0,8.2,86.0,2.0,18.0,4.0
21,E022,Manoj,IT,33.0,Male,8.0,Hybrid,12.0,8.4,88.0,3.0,19.0,4.0
22,E023,Neha,HR,27.0,Female,4.0,Remote,7.0,7.2,74.0,6.0,10.0,2.0
23,E024,Aravind,Finance,35.0,Male,9.0,Office,14.0,8.9,91.0,2.0,22.0,5.0
24,E025,Deepa,Marketing,28.0,Female,5.0,Hybrid,9.0,7.5,79.0,4.0,15.0,3.0
25,E026,Suresh,IT,37.0,Male,12.0,Office,16.0,9.2,94.0,2.0,25.0,5.0
26,E027,Kavya,HR,29.0,Female,6.0,Remote,8.0,7.4,76.0,5.0,13.0,3.0
27,E028,Ajay,Finance,32.0,Male,7.0,Hybrid,11.0,8.1,85.0,3.0,18.0,4.0
28,E029,Reshma,Marketing,30.0,Female,5.0,Office,9.0,7.6,80.0,4.0,14.0,3.0
29,E030,Vikram,IT,34.0,Male,8.0,Remote,13.0,8.7,90.0,2.0,21.0,4.0
30,E031,Shyam,HR,31.0,Male,7.0,Hybrid,10.0,8.0,83.0,3.0,16.0,4.0
31,E032,Pooja,Finance,26.0,Female,3.0,Office,7.0,7.1,75.0,5.0,11.0,2.0
32,E033,Harish,Marketing,35.0,Male,9.0,Remote,12.0,8.5,88.0,2.0,19.0,4.0
33,E034,Anjali,IT,28.0,Female,4.0,Hybrid,8.0,7.6,79.0,4.0,13.0,3.0
34,E035,George,Finance,36.0,Male,10.0,Office,15.0,9.0,92.0,2.0,23.0,5.0
35,E036,Lakshmi,HR,33.0,Female,8.0,Remote,10.0,8.2,84.0,3.0,17.0,4.0
36,E037,Ajith,Marketing,29.0,Male,6.0,Hybrid,9.0,7.7,81.0,4.0,15.0,3.0
37,E038,Farah,IT,27.0,Female,3.0,Office,7.0,7.2,74.0,5.0,10.0,2.0
38,E039,Manu,Finance,34.0,Male,8.0,Remote,12.0,8.4,87.0,3.0,20.0,4.0
39,E040,Sneha,HR,30.0,Female,5.0,Hybrid,9.0,7.5,80.0,4.0,14.0,3.0
40,E041,Daniel,Marketing,32.0,Male,7.0,Office,11.0,8.1,85.0,3.0,18.0,4.0
41,E042,Rohit,IT,35.0,Male,9.0,Remote,14.0,8.8,91.0,2.0,22.0,5.0
42,E043,Maya,Finance,28.0,Female,4.0,Hybrid,8.0,7.3,77.0,5.0,12.0,3.0
43,E044,Nikhil,Marketing,31.0,Male,6.0,Office,10.0,7.9,83.0,3.0,16.0,4.0
44,E045,Alina,HR,29.0,Female,5.0,Remote,8.0,7.4,78.0,4.0,13.0,3.0
45,E046,Prakash,IT,37.0,Male,11.0,Office,16.0,9.1,93.0,2.0,24.0,5.0
46,E047,Tina,Finance,27.0,Female,3.0,Hybrid,7.0,7.2,74.0,6.0,11.0,2.0
47,E048,Ramesh,Marketing,34.0,Male,8.0,Remote,12.0,8.3,88.0,3.0,19.0,4.0
48,E049,Sonia,HR,30.0,Female,6.0,Office,9.0,7.6,81.0,4.0,15.0,3.0
49,E050,Abdul,IT,33.0,Male,7.0,Hybrid,11.0,8.2,86.0,3.0,18.0,4.0

## Identify null values in each column

In [2]:
df.isna().sum()

Employee_ID           0
Name                  0
Department            0
Age                   1
Gender                0
Experience_Years      1
Work_Mode             0
Projects_Completed    1
Avg_Daily_Hours       1
Performance_Score     1
Sick_Days             1
Training_Hours        1
Job_Satisfaction      1
dtype: int64

## Replace Missing Age with average age

In [3]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

## Replace Missing Experience Years With Median

In [4]:
df['Experience_Years'].fillna(df['Experience_Years'].median(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\4283573778.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Experience_Years'].fillna(df['Experience_Years'].median(),inplace=True)

## Fill Missing Job Satisfaction With Mode

In [27]:
df['Job_Satisfaction'].fillna(df['Job_Satisfaction'].mode(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\1246339762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Job_Satisfaction'].fillna(df['Job_Satisfaction'].mode(),inplace=True)

## Remove Duplicate Values

In [28]:
df.drop_duplicates(inplace=True)

In [29]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Gender',
       'Experience_Years', 'Work_Mode', 'Projects_Completed',
       'Avg_Daily_Hours', 'Performance_Score', 'Sick_Days', 'Training_Hours',
       'Job_Satisfaction'],
      dtype='object')


## Replace Missing Avg Daily Hours with Average

In [30]:
df['Avg_Daily_Hours'].fillna(df['Avg_Daily_Hours'].mean(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\2036637530.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Avg_Daily_Hours'].fillna(df['Avg_Daily_Hours'].mean(),inplace=True)

In [31]:
df

,Employee_ID,Name,Department,Age,Gender,Experience_Years,Work_Mode,Projects_Completed,Avg_Daily_Hours,Performance_Score,Sick_Days,Training_Hours,Job_Satisfaction
0,E001,Amit,IT,29.000000,Male,5.0,Remote,12.000000,8.500000,88.0,3.0,20.0,4.0
1,E002,Sara,HR,34.000000,Female,8.0,Office,9.000000,7.500000,82.0,5.0,15.0,3.0
2,E003,Rahul,Finance,31.000000,Male,6.0,Hybrid,11.000000,8.000000,85.0,2.0,18.0,4.0
3,E004,Priya,IT,27.000000,Female,3.0,Remote,8.000000,7.800000,80.0,1.0,12.0,3.0
4,E005,John,Marketing,36.000000,Male,10.0,Office,15.000000,9.000000,92.0,4.0,22.0,5.0
5,E006,Anita,HR,28.000000,Female,4.0,Hybrid,7.000000,7.200000,75.0,6.0,10.0,2.0
6,E007,Arjun,IT,30.000000,Male,6.0,Remote,13.000000,8.600000,89.0,2.0,20.0,4.0
7,E008,Meera,Finance,33.000000,Female,7.0,Office,10.000000,8.100000,84.0,3.0,17.0,4.0
8,E009,Kiran,Marketing,29.000000,Male,5.0,Hybrid,9.000000,7.600000,78.0,4.0,14.0,3.0
9,E010,David,IT,35.000000,Male,9.0,Office,14.000000,8.800000,91.0,2.0,21.0,5.0
10,E011,Linda,HR,31.142857,Female,6.0,Remote,8.000000,7.400000,76.0,5.0,13.0,3.0
11,E012,Ravi,Finance,32.000000,Male,6.0,Hybrid,11.000000,8.200000,86.0,3.0,18.0,4.0
12,E013,Nina,Marketing,26.000000,Female,3.0,Office,7.000000,7.100000,NaN,4.0,12.0,3.0
13,E014,Sunil,IT,31.000000,Male,7.0,Remote,12.000000,8.300000,87.0,NaN,19.0,4.0
14,E015,Asha,HR,29.000000,Female,5.0,Hybrid,9.000000,7.700000,80.0,3.0,NaN,3.0
15,E016,Karthik,Finance,34.000000,Male,8.0,Office,10.000000,7.991837,83.0,2.0,17.0,4.0
16,E017,Divya,Marketing,27.000000,Female,4.0,Remote,8.000000,7.300000,77.0,5.0,11.0,4.0
17,E018,Joseph,IT,36.000000,Male,11.0,Office,16.000000,9.100000,93.0,2.0,24.0,5.0
18,E019,Anu,HR,30.000000,Female,6.0,Hybrid,9.000000,7.600000,81.0,4.0,14.0,3.0
19,E020,Varun,Finance,28.000000,Male,4.0,Remote,10.469388,7.500000,79.0,3.0,13.0,3.0
20,E021,Riya,Marketing,31.000000,Female,6.0,Office,11.000000,8.200000,86.0,2.0,18.0,4.0
21,E022,Manoj,IT,33.000000,Male,8.0,Hybrid,12.000000,8.400000,88.0,3.0,19.0,4.0
22,E023,Neha,HR,27.000000,Female,4.0,Remote,7.000000,7.200000,74.0,6.0,10.0,2.0
23,E024,Aravind,Finance,35.000000,Male,9.0,Office,14.000000,8.900000,91.0,2.0,22.0,5.0
24,E025,Deepa,Marketing,28.000000,Female,5.0,Hybrid,9.000000,7.500000,79.0,4.0,15.0,3.0
25,E026,Suresh,IT,37.000000,Male,12.0,Office,16.000000,9.200000,94.0,2.0,25.0,5.0
26,E027,Kavya,HR,29.000000,Female,6.0,Remote,8.000000,7.400000,76.0,5.0,13.0,3.0
27,E028,Ajay,Finance,32.000000,Male,7.0,Hybrid,11.000000,8.100000,85.0,3.0,18.0,4.0
28,E029,Reshma,Marketing,30.000000,Female,5.0,Office,9.000000,7.600000,80.0,4.0,14.0,3.0
29,E030,Vikram,IT,34.000000,Male,8.0,Remote,13.000000,8.700000,90.0,2.0,21.0,4.0
30,E031,Shyam,HR,31.000000,Male,7.0,Hybrid,10.000000,8.000000,83.0,3.0,16.0,4.0
31,E032,Pooja,Finance,26.000000,Female,3.0,Office,7.000000,7.100000,75.0,5.0,11.0,2.0
32,E033,Harish,Marketing,35.000000,Male,9.0,Remote,12.000000,8.500000,88.0,2.0,19.0,4.0
33,E034,Anjali,IT,28.000000,Female,4.0,Hybrid,8.000000,7.600000,79.0,4.0,13.0,3.0
34,E035,George,Finance,36.000000,Male,10.0,Office,15.000000,9.000000,92.0,2.0,23.0,5.0
35,E036,Lakshmi,HR,33.000000,Female,8.0,Remote,10.000000,8.200000,84.0,3.0,17.0,4.0
36,E037,Ajith,Marketing,29.000000,Male,6.0,Hybrid,9.000000,7.700000,81.0,4.0,15.0,3.0
37,E038,Farah,IT,27.000000,Female,3.0,Office,7.000000,7.200000,74.0,5.0,10.0,2.0
38,E039,Manu,Finance,34.000000,Male,8.0,Remote,12.000000,8.400000,87.0,3.0,20.0,4.0
39,E040,Sneha,HR,30.000000,Female,5.0,Hybrid,9.000000,7.500000,80.0,4.0,14.0,3.0
40,E041,Daniel,Marketing,32.000000,Male,7.0,Office,11.000000,8.100000,85.0,3.0,18.0,4.0
41,E042,Rohit,IT,35.000000,Male,9.0,Remote,14.000000,8.800000,91.0,2.0,22.0,5.0
42,E043,Maya,Finance,28.000000,Female,4.0,Hybrid,8.000000,7.300000,77.0,5.0,12.0,3.0
43,E044,Nikhil,Marketing,31.000000,Male,6.0,Office,10.000000,7.900000,83.0,3.0,16.0,4.0
44,E045,Alina,HR,29.000000,Female,5.0,Remote,8.000000,7.400000,78.0,4.0,13.0,3.0
45,E046,Prakash,IT,37.000000,Male,11.0,Office,16.000000,9.100000,93.0,2.0,24.0,5.0
46,E047,Tina,Finance,27.000000,Female,3.0,Hybrid,7.000000,7.200000,74.0,6.0,11.0,2.0
47,E048,Ramesh,Marketing,34.000000,Male,8.0,Remote,12.000000,8.300000,88.0,3.0,19.0,4.0
48,E049,Sonia,HR,30.000000,Female,6.0,Office,9.000000,7.600000,81.0,4.0,15.0,3.0
49,E050,Abdul,IT,33.000000,Male,7.0,Hybrid,11.000000,8.200000,86.0,3.0,18.0,4.0

## Replace Missing Value Project Completed with Average

In [32]:
df['Projects_Completed'].fillna(df['Projects_Completed'].mean(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\1060148083.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Projects_Completed'].fillna(df['Projects_Completed'].mean(),inplace=True)

## Replace Missing Performance Sore with Average

In [34]:
df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\1041889571.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)

## Replace Missing Sick Days With 0

In [36]:
df['Sick_Days'].fillna(0,inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\1154007418.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Sick_Days'].fillna(0,inplace=True)

## Replace Missing Training Hours With Average

In [37]:
df['Training_Hours'].fillna(df['Training_Hours'].mean(),inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13136\2527920218.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Training_Hours'].fillna(df['Training_Hours'].mean(),inplace=True)

In [38]:
df.isna().sum()

Employee_ID           0
Name                  0
Department            0
Age                   0
Gender                0
Experience_Years      0
Work_Mode             0
Projects_Completed    0
Avg_Daily_Hours       0
Performance_Score     0
Sick_Days             0
Training_Hours        0
Job_Satisfaction      0
dtype: int64

## Convert Avg Daily Hours to Int

In [39]:
df['Avg_Daily_Hours'] = df['Avg_Daily_Hours'].astype(int)

In [41]:
df['Productivity_Index'] = df['Projects_Completed']*df['Performance_Score']/100

In [42]:
df

,Employee_ID,Name,Department,Age,Gender,Experience_Years,Work_Mode,Projects_Completed,Avg_Daily_Hours,Performance_Score,Sick_Days,Training_Hours,Job_Satisfaction,Productivity_Index
0,E001,Amit,IT,29.000000,Male,5.0,Remote,12.000000,8,88.000000,3.0,20.00000,4.0,10.560000
1,E002,Sara,HR,34.000000,Female,8.0,Office,9.000000,7,82.000000,5.0,15.00000,3.0,7.380000
2,E003,Rahul,Finance,31.000000,Male,6.0,Hybrid,11.000000,8,85.000000,2.0,18.00000,4.0,9.350000
3,E004,Priya,IT,27.000000,Female,3.0,Remote,8.000000,7,80.000000,1.0,12.00000,3.0,6.400000
4,E005,John,Marketing,36.000000,Male,10.0,Office,15.000000,9,92.000000,4.0,22.00000,5.0,13.800000
5,E006,Anita,HR,28.000000,Female,4.0,Hybrid,7.000000,7,75.000000,6.0,10.00000,2.0,5.250000
6,E007,Arjun,IT,30.000000,Male,6.0,Remote,13.000000,8,89.000000,2.0,20.00000,4.0,11.570000
7,E008,Meera,Finance,33.000000,Female,7.0,Office,10.000000,8,84.000000,3.0,17.00000,4.0,8.400000
8,E009,Kiran,Marketing,29.000000,Male,5.0,Hybrid,9.000000,7,78.000000,4.0,14.00000,3.0,7.020000
9,E010,David,IT,35.000000,Male,9.0,Office,14.000000,8,91.000000,2.0,21.00000,5.0,12.740000
10,E011,Linda,HR,31.142857,Female,6.0,Remote,8.000000,7,76.000000,5.0,13.00000,3.0,6.080000
11,E012,Ravi,Finance,32.000000,Male,6.0,Hybrid,11.000000,8,86.000000,3.0,18.00000,4.0,9.460000
12,E013,Nina,Marketing,26.000000,Female,3.0,Office,7.000000,7,83.428571,4.0,12.00000,3.0,5.840000
13,E014,Sunil,IT,31.000000,Male,7.0,Remote,12.000000,8,87.000000,0.0,19.00000,4.0,10.440000
14,E015,Asha,HR,29.000000,Female,5.0,Hybrid,9.000000,7,80.000000,3.0,16.55102,3.0,7.200000
15,E016,Karthik,Finance,34.000000,Male,8.0,Office,10.000000,7,83.000000,2.0,17.00000,4.0,8.300000
16,E017,Divya,Marketing,27.000000,Female,4.0,Remote,8.000000,7,77.000000,5.0,11.00000,4.0,6.160000
17,E018,Joseph,IT,36.000000,Male,11.0,Office,16.000000,9,93.000000,2.0,24.00000,5.0,14.880000
18,E019,Anu,HR,30.000000,Female,6.0,Hybrid,9.000000,7,81.000000,4.0,14.00000,3.0,7.290000
19,E020,Varun,Finance,28.000000,Male,4.0,Remote,10.469388,7,79.000000,3.0,13.00000,3.0,8.270816
20,E021,Riya,Marketing,31.000000,Female,6.0,Office,11.000000,8,86.000000,2.0,18.00000,4.0,9.460000
21,E022,Manoj,IT,33.000000,Male,8.0,Hybrid,12.000000,8,88.000000,3.0,19.00000,4.0,10.560000
22,E023,Neha,HR,27.000000,Female,4.0,Remote,7.000000,7,74.000000,6.0,10.00000,2.0,5.180000
23,E024,Aravind,Finance,35.000000,Male,9.0,Office,14.000000,8,91.000000,2.0,22.00000,5.0,12.740000
24,E025,Deepa,Marketing,28.000000,Female,5.0,Hybrid,9.000000,7,79.000000,4.0,15.00000,3.0,7.110000
25,E026,Suresh,IT,37.000000,Male,12.0,Office,16.000000,9,94.000000,2.0,25.00000,5.0,15.040000
26,E027,Kavya,HR,29.000000,Female,6.0,Remote,8.000000,7,76.000000,5.0,13.00000,3.0,6.080000
27,E028,Ajay,Finance,32.000000,Male,7.0,Hybrid,11.000000,8,85.000000,3.0,18.00000,4.0,9.350000
28,E029,Reshma,Marketing,30.000000,Female,5.0,Office,9.000000,7,80.000000,4.0,14.00000,3.0,7.200000
29,E030,Vikram,IT,34.000000,Male,8.0,Remote,13.000000,8,90.000000,2.0,21.00000,4.0,11.700000
30,E031,Shyam,HR,31.000000,Male,7.0,Hybrid,10.000000,8,83.000000,3.0,16.00000,4.0,8.300000
31,E032,Pooja,Finance,26.000000,Female,3.0,Office,7.000000,7,75.000000,5.0,11.00000,2.0,5.250000
32,E033,Harish,Marketing,35.000000,Male,9.0,Remote,12.000000,8,88.000000,2.0,19.00000,4.0,10.560000
33,E034,Anjali,IT,28.000000,Female,4.0,Hybrid,8.000000,7,79.000000,4.0,13.00000,3.0,6.320000
34,E035,George,Finance,36.000000,Male,10.0,Office,15.000000,9,92.000000,2.0,23.00000,5.0,13.800000
35,E036,Lakshmi,HR,33.000000,Female,8.0,Remote,10.000000,8,84.000000,3.0,17.00000,4.0,8.400000
36,E037,Ajith,Marketing,29.000000,Male,6.0,Hybrid,9.000000,7,81.000000,4.0,15.00000,3.0,7.290000
37,E038,Farah,IT,27.000000,Female,3.0,Office,7.000000,7,74.000000,5.0,10.00000,2.0,5.180000
38,E039,Manu,Finance,34.000000,Male,8.0,Remote,12.000000,8,87.000000,3.0,20.00000,4.0,10.440000
39,E040,Sneha,HR,30.000000,Female,5.0,Hybrid,9.000000,7,80.000000,4.0,14.00000,3.0,7.200000
40,E041,Daniel,Marketing,32.000000,Male,7.0,Office,11.000000,8,85.000000,3.0,18.00000,4.0,9.350000
41,E042,Rohit,IT,35.000000,Male,9.0,Remote,14.000000,8,91.000000,2.0,22.00000,5.0,12.740000
42,E043,Maya,Finance,28.000000,Female,4.0,Hybrid,8.000000,7,77.000000,5.0,12.00000,3.0,6.160000
43,E044,Nikhil,Marketing,31.000000,Male,6.0,Office,10.000000,7,83.000000,3.0,16.00000,4.0,8.300000
44,E045,Alina,HR,29.000000,Female,5.0,Remote,8.000000,7,78.000000,4.0,13.00000,3.0,6.240000
45,E046,Prakash,IT,37.000000,Male,11.0,Office,16.000000,9,93.000000,2.0,24.00000,5.0,14.880000
46,E047,Tina,Finance,27.000000,Female,3.0,Hybrid,7.000000,7,74.000000,6.0,11.00000,2.0,5.180000
47,E048,Ramesh,Marketing,34.000000,Male,8.0,Remote,12.000000,8,88.000000,3.0,19.00000,4.0,10.560000
48,E049,Sonia,HR,30.000000,Female,6.0,Office,9.000000,7,81.000000,4.0,15.00000,3.0,7.290000
49,E050,Abdul,IT,33.000000,Male,7.0,Hybrid,11.000000,8,86.000000,3.0,18.00000,4.0,9.460000

## Create New Column Performance Level

In [44]:
def pl(score):
    if score < 75:
        return 'Low'
    elif score >= 75 and score <= 85:
        return 'Medium'
    else:
        return 'High'

df['Performance_Level'] = df['Performance_Score'].apply(pl)

In [45]:
df[['Performance_Score','Performance_Level']]

    Performance_Score Performance_Level
0           88.000000              High
1           82.000000            Medium
2           85.000000            Medium
3           80.000000            Medium
4           92.000000              High
5           75.000000            Medium
6           89.000000              High
7           84.000000            Medium
8           78.000000            Medium
9           91.000000              High
10          76.000000            Medium
11          86.000000              High
12          83.428571            Medium
13          87.000000              High
14          80.000000            Medium
15          83.000000            Medium
16          77.000000            Medium
17          93.000000              High
18          81.000000            Medium
19          79.000000            Medium
20          86.000000              High
21          88.000000              High
22          74.000000               Low
23          91.000000              High
24          79.000000            Medium
25          94.000000              High
26          76.000000            Medium
27          85.000000            Medium
28          80.000000            Medium
29          90.000000              High
30          83.000000            Medium
31          75.000000            Medium
32          88.000000              High
33          79.000000            Medium
34          92.000000              High
35          84.000000            Medium
36          81.000000            Medium
37          74.000000               Low
38          87.000000              High
39          80.000000            Medium
40          85.000000            Medium
41          91.000000              High
42          77.000000            Medium
43          83.000000            Medium
44          78.000000            Medium
45          93.000000              High
46          74.000000               Low
47          88.000000              High
48          81.000000            Medium
49          86.000000              High

In [46]:
from sqlalchemy import create_engine

user = 'root'
password = 'toor'
host = 'localhost'
port = 3306
database = 'employee_work_pattern'
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

df.to_sql(
    name='employee',
    con=engine,
    if_exists='replace',
    index=False
)

50